# Welding path configuration
welding_path:
  start_point: [0.1, -0.55, 0.0]
  end_point: [-0.1, -0.55, 0.0]
  num_timesteps: 750
  rotation:
    roll: 0.0
    pitch: 0.785398  # pi/4 in radians
    yaw: -1.570796    # pi/2 in radians

welding_path_from_object: True
welding_object:
  parent: mid_sole_link
  object_dir: "eetrack/weld_objects"
  # yaw: 0.0 # pi/2
  pose: [1.0, 0.0, 0.0, 0.0, 0.35, -0.25, 0.3] # wxyz_xyz
  object_name: "Circular_Body_Plate_110_80"
  segment_normal_deg_range: [179.0, 181.0]
  # pose: [0.0, 0.0, 0.0, 1.0, 0.35, -0.25, 0.3] # wxyz_xyz
  # object_name: "Circular_Plate_50"
  # segment_normal_deg_range: [-30.0, 30.0]
  segment_length_per_timestep: 0.0002  # 0.1 m/s * 0.02 s (vel * dt)
  offset_length: 0.02
  approach_deg: 45.0

# Batch search space settings
search_space:
  z_height: 0.3
  x_range: [-0.4, 0.8]      # [min, max]
  y_range: [-0.9, 0.4]    # [min, max]
  angle_range: [-1.5707963267, 1.5707963267] # [min, max] (rad)
  # x_range: [0.35, 0.35]      # [min, max]
  # y_range: [-0.25, -0.25]    # [min, max]
  # angle_range: [0.0, 0.0] # [min, max] (rad)
  n_samples: 100000
  batch_size: 100

# Robot configuration
robot:
  urdf_path: "eetrack/robots/g1_29dof_rev_1_0_ver4_camera_mount_v4.urdf"
  movable_joints:
    - "right_shoulder_pitch_joint"
    - "right_shoulder_roll_joint"
    - "right_shoulder_yaw_joint"
    - "right_elbow_joint"
    - "right_wrist_pitch_joint"
    - "right_wrist_roll_joint"
    - "right_wrist_yaw_joint"
  sit_terminal_states_path: eetrack/sit_terminal_states.npz
  sit_target_height: 0.37

# Optimization weights
weights:
  position_tracking: 100.0
  orientation_tracking: 50.0
  smoothness: 20.0
  joint_limits: 1.0
  collision: 1.0
  rest_pose: 0.0

# Collision settings
collision:
  safety_margin: -0.02  # Collision safety margin (meters)
  ignore_adjacent_links: true
  only_movable_links: true
  exclude_links: [
    "head_link", "camera_color_optical_frame", "camera_link", 
    "d435_link", "d435_mount_1_link", "d435_mount_2_link", 
    "mid360_link", "mid360_link_IMU", "mid360_link_frame",
    "left_shoulder_pitch_link", "left_shoulder_roll_link", "left_shoulder_yaw_link", 
    "left_elbow_link", "left_wrist_pitch_link", "left_wrist_roll_link", 
    "left_wrist_yaw_link", "left_rubber_hand", "left_hip_pitch_link", "left_hip_roll_link", "left_hip_yaw_link", "left_knee_link", 
    "left_ankle_pitch_link", "left_ankle_roll_link", "left_sole_link", "right_ankle_pitch_link", "right_ankle_roll_link", "right_sole_link"
  ]
  ignore_pairs: [
    ["right_wrist_yaw_link", "right_wrist_roll_link"],
    ["right_wrist_pitch_link", "right_elbow_link"]
  ]
  required_collision_links: [
    "right_shoulder_pitch_link", "right_shoulder_roll_link", "right_shoulder_yaw_link",
    "right_elbow_link", "right_wrist_pitch_link", "right_wrist_roll_link",
    "right_wrist_yaw_link", "welder", "welder2", "end_effector"
  ]

# Visualization settings
visualization:
  target_color: [255, 0, 0]  # Red
  point_size: 0.01
  sleep_time: 0.05

# Error tolerance settings
tolerance:
  position_error: 0.005  # Position error tolerance (meters)
  orientation_error: 0.087  # Orientation error tolerance (radians) - ~5 degrees

optimization:
  max_iterations: 50
collision_pairs:
  - [right_shoulder_pitch_link, pelvis]
  - [right_shoulder_pitch_link, pelvis_contour_link]
  - [right_shoulder_pitch_link, right_hip_pitch_link]
  - [right_shoulder_pitch_link, right_hip_roll_link]
  - [right_shoulder_pitch_link, right_hip_yaw_link]
  - [right_shoulder_pitch_link, right_knee_link]
  - [right_shoulder_pitch_link, waist_yaw_link]
  - [right_shoulder_pitch_link, waist_roll_link]
  - [right_shoulder_pitch_link, logo_link]
  - [right_shoulder_pitch_link, imu_in_torso]
  - [right_shoulder_pitch_link, imu_in_pelvis]
  - [right_shoulder_roll_link, pelvis]
  - [right_shoulder_roll_link, pelvis_contour_link]
  - [right_shoulder_roll_link, right_hip_pitch_link]
  - [right_shoulder_roll_link, right_hip_roll_link]
  - [right_shoulder_roll_link, right_hip_yaw_link]
  - [right_shoulder_roll_link, right_knee_link]
  - [right_shoulder_roll_link, waist_yaw_link]
  - [right_shoulder_roll_link, waist_roll_link]
  - [right_shoulder_roll_link, torso_link]
  - [right_shoulder_roll_link, logo_link]
  - [right_shoulder_roll_link, imu_in_torso]
  - [right_shoulder_roll_link, imu_in_pelvis]
  - [right_shoulder_yaw_link, pelvis]
  - [right_shoulder_yaw_link, pelvis_contour_link]
  - [right_shoulder_yaw_link, right_hip_pitch_link]
  - [right_shoulder_yaw_link, right_hip_roll_link]
  - [right_shoulder_yaw_link, right_hip_yaw_link]
  - [right_shoulder_yaw_link, right_knee_link]
  - [right_shoulder_yaw_link, waist_yaw_link]
  - [right_shoulder_yaw_link, waist_roll_link]
  - [right_shoulder_yaw_link, torso_link]
  - [right_shoulder_yaw_link, logo_link]
  - [right_shoulder_yaw_link, imu_in_torso]
  - [right_shoulder_yaw_link, imu_in_pelvis]
  - [right_shoulder_yaw_link, right_shoulder_pitch_link]
  - [right_elbow_link, pelvis]
  - [right_elbow_link, pelvis_contour_link]
  - [right_elbow_link, right_hip_pitch_link]
  - [right_elbow_link, right_hip_roll_link]
  - [right_elbow_link, right_hip_yaw_link]
  - [right_elbow_link, right_knee_link]
  - [right_elbow_link, waist_yaw_link]
  - [right_elbow_link, waist_roll_link]
  - [right_elbow_link, torso_link]
  - [right_elbow_link, logo_link]
  - [right_elbow_link, imu_in_torso]
  - [right_elbow_link, imu_in_pelvis]
  - [right_elbow_link, right_shoulder_pitch_link]
  - [right_elbow_link, right_shoulder_roll_link]
  - [right_wrist_roll_link, pelvis]
  - [right_wrist_roll_link, pelvis_contour_link]
  - [right_wrist_roll_link, right_hip_pitch_link]
  - [right_wrist_roll_link, right_hip_roll_link]
  - [right_wrist_roll_link, right_hip_yaw_link]
  - [right_wrist_roll_link, right_knee_link]
  - [right_wrist_roll_link, waist_yaw_link]
  - [right_wrist_roll_link, waist_roll_link]
  - [right_wrist_roll_link, torso_link]
  - [right_wrist_roll_link, logo_link]
  - [right_wrist_roll_link, imu_in_torso]
  - [right_wrist_roll_link, imu_in_pelvis]
  - [right_wrist_roll_link, right_shoulder_pitch_link]
  - [right_wrist_roll_link, right_shoulder_roll_link]
  - [right_wrist_roll_link, right_shoulder_yaw_link]
  - [right_wrist_pitch_link, pelvis]
  - [right_wrist_pitch_link, pelvis_contour_link]
  - [right_wrist_pitch_link, right_hip_pitch_link]
  - [right_wrist_pitch_link, right_hip_roll_link]
  - [right_wrist_pitch_link, right_hip_yaw_link]
  - [right_wrist_pitch_link, right_knee_link]
  - [right_wrist_pitch_link, waist_yaw_link]
  - [right_wrist_pitch_link, waist_roll_link]
  - [right_wrist_pitch_link, torso_link]
  - [right_wrist_pitch_link, logo_link]
  - [right_wrist_pitch_link, imu_in_torso]
  - [right_wrist_pitch_link, imu_in_pelvis]
  - [right_wrist_pitch_link, right_shoulder_pitch_link]
  - [right_wrist_pitch_link, right_shoulder_roll_link]
  - [right_wrist_pitch_link, right_shoulder_yaw_link]
  - [right_wrist_yaw_link, pelvis]
  - [right_wrist_yaw_link, pelvis_contour_link]
  - [right_wrist_yaw_link, right_hip_pitch_link]
  - [right_wrist_yaw_link, right_hip_roll_link]
  - [right_wrist_yaw_link, right_hip_yaw_link]
  - [right_wrist_yaw_link, right_knee_link]
  - [right_wrist_yaw_link, waist_yaw_link]
  - [right_wrist_yaw_link, waist_roll_link]
  - [right_wrist_yaw_link, torso_link]
  - [right_wrist_yaw_link, logo_link]
  - [right_wrist_yaw_link, imu_in_torso]
  - [right_wrist_yaw_link, imu_in_pelvis]
  - [right_wrist_yaw_link, right_shoulder_pitch_link]
  - [right_wrist_yaw_link, right_shoulder_roll_link]
  - [right_wrist_yaw_link, right_shoulder_yaw_link]
  - [right_wrist_yaw_link, right_elbow_link]
  - [welder, pelvis]
  - [welder, pelvis_contour_link]
  - [welder, right_hip_pitch_link]
  - [welder, right_hip_roll_link]
  - [welder, right_hip_yaw_link]
  - [welder, right_knee_link]
  - [welder, waist_yaw_link]
  - [welder, waist_roll_link]
  - [welder, torso_link]
  - [welder, logo_link]
  - [welder, imu_in_torso]
  - [welder, imu_in_pelvis]
  - [welder, right_shoulder_pitch_link]
  - [welder, right_shoulder_roll_link]
  - [welder, right_shoulder_yaw_link]
  - [welder, right_elbow_link]
  - [welder, right_wrist_roll_link]
  # - [welder, right_wrist_pitch_link]
  - [welder2, pelvis]
  - [welder2, pelvis_contour_link]
  - [welder2, right_hip_pitch_link]
  - [welder2, right_hip_roll_link]
  - [welder2, right_hip_yaw_link]
  - [welder2, right_knee_link]
  - [welder2, waist_yaw_link]
  - [welder2, waist_roll_link]
  - [welder2, torso_link]
  - [welder2, logo_link]
  - [welder2, imu_in_torso]
  - [welder2, imu_in_pelvis]
  - [welder2, right_shoulder_pitch_link]
  - [welder2, right_shoulder_roll_link]
  - [welder2, right_shoulder_yaw_link]
  - [welder2, right_elbow_link]
  - [welder2, right_wrist_roll_link]
  - [welder2, right_wrist_pitch_link]
  - [welder2, right_wrist_yaw_link]
  - [end_effector, pelvis]
  - [end_effector, pelvis_contour_link]
  - [end_effector, right_hip_pitch_link]
  - [end_effector, right_hip_roll_link]
  - [end_effector, right_hip_yaw_link]
  - [end_effector, right_knee_link]
  - [end_effector, waist_yaw_link]
  - [end_effector, waist_roll_link]
  - [end_effector, torso_link]
  - [end_effector, logo_link]
  - [end_effector, imu_in_torso]
  - [end_effector, imu_in_pelvis]
  - [end_effector, right_shoulder_pitch_link]
  - [end_effector, right_shoulder_roll_link]
  - [end_effector, right_shoulder_yaw_link]
  - [end_effector, right_elbow_link]
  - [end_effector, right_wrist_roll_link]
  - [end_effector, right_wrist_pitch_link]
  - [end_effector, right_wrist_yaw_link]
