# Welding path configuration
welding_path:
  start_point: [0.1, -0.55, 0.0]
  end_point: [-0.1, -0.55, 0.0]
  num_timesteps: 750
  rotation:
    roll: 0.0
    pitch: 0.785398  # pi/4 in radians
    yaw: -1.570796    # pi/2 in radians

welding_path_from_object: True
welding_object:
  parent: mid_sole_link
  object_dir: "eetrack/weld_objects"
  # yaw: 1.5707963268 # pi/2
  # pose: [1.0, 0.0, 0.0, 0.0, 0.35, -0.25, 0.3] # wxyz_xyz
  object_name: "Circular_Body_Plate_110_80"
  segment_normal_deg_range: [179.0, 181.0]
  # pose: [0.0, 0.0, 0.0, 1.0, 0.35, -0.25, 0.3] # wxyz_xyz
  # object_name: "Circular_Plate_50"
  # segment_normal_deg_range: [-30.0, 30.0]
  segment_length_per_timestep: 0.0002  # 0.1 m/s * 0.02 s (vel * dt)
  offset_length: 0.02
  approach_deg: 45.0

# Batch search space settings
search_space:
  z_height: 0.3
  x_range: [-0.3, 0.3]      # [min, max]
  y_range: [-0.5, -0.1]    # [min, max]
  angle_range: [-1.570796, 1.570796] # [min, max] (rad)

# Robot configuration
robot:
  urdf_path: "eetrack/robots/g1_29dof_rev_1_0_ver4_camera_mount_v4.urdf"
  movable_joints:
    - "right_shoulder_pitch_joint"
    - "right_shoulder_roll_joint"
    - "right_shoulder_yaw_joint"
    - "right_elbow_joint"
    - "right_wrist_pitch_joint"
    - "right_wrist_roll_joint"
    - "right_wrist_yaw_joint"
  sit_terminal_states_path: eetrack/sit_terminal_states.npz
  sit_target_height: 0.37

# Optimization weights
weights:
  position_tracking: 200.0
  orientation_tracking: 100.0
  smoothness: 50.0
  joint_limits: 100.0
  collision: 0.5

# Collision settings
collision:
  safety_margin: 0.05  # Collision safety margin (meters)
  ignore_adjacent_links: true
  only_movable_links: true
  exclude_links: [
    "head_link", "camera_color_optical_frame", "camera_link", 
    "d435_link", "d435_mount_1_link", "d435_mount_2_link", 
    "mid360_link", "mid360_link_IMU", "mid360_link_frame",
    "left_shoulder_pitch_link", "left_shoulder_roll_link", "left_shoulder_yaw_link", 
    "left_elbow_link", "left_wrist_pitch_link", "left_wrist_roll_link", 
    "left_wrist_yaw_link", "left_rubber_hand", "left_hip_pitch_link", "left_hip_roll_link", "left_hip_yaw_link", "left_knee_link", 
    "left_ankle_pitch_link", "left_ankle_roll_link", "left_sole_link"
  ]
  ignore_pairs: [
    ["right_wrist_yaw_link", "right_wrist_roll_link"],
    ["right_wrist_pitch_link", "right_elbow_link"]
  ]

# Visualization settings
visualization:
  target_color: [255, 0, 0]  # Red
  point_size: 0.02
  sleep_time: 0.05

# Error tolerance settings
tolerance:
  position_error: 0.05  # Position error tolerance (meters)
  orientation_error: 0.087  # Orientation error tolerance (radians) - ~5 degrees

optimization:
  max_iterations: 30