# Welding path configuration
welding_path:
  start_point: [0.1, -0.55, 0.0]
  end_point: [-0.1, -0.55, 0.0]
  num_timesteps: 750
  rotation:
    roll: 0.0
    pitch: 0.785398  # pi/4 in radians
    yaw: -1.570796    # pi/2 in radians

welding_path_from_object: True
welding_object_pose: [0.7071, 0.0, 0.0, 0.7071, 0.4, -0.2, 0.0] # wxyz_xyz
welding_object:
  object_dir: "eetrack/weld_objects"
  object_name: "Circular_Body_Plate_110_80"
  segment_normal_deg_range: [89.0, 91.0]
  # object_name: "Circular_Plate_50"
  # segment_normal_deg_range: [60.0, 120.0]
  segment_length_per_timestep: 0.0002  # 0.1 m/s * 0.02 s (vel * dt)
  offset_length: 0.02
  approach_deg: 45.0

# Robot configuration
robot:
  urdf_path: "eetrack/robots/g1_29dof_rev_1_0_ver4_camera_mount_v4.urdf"
  movable_joints:
    - "right_shoulder_pitch_joint"
    - "right_shoulder_roll_joint"
    - "right_shoulder_yaw_joint"
    - "right_elbow_joint"
    - "right_wrist_pitch_joint"
    - "right_wrist_roll_joint"
    - "right_wrist_yaw_joint"

# Optimization weights
weights:
  position_tracking: 100.0
  orientation_tracking: 50.0
  smoothness: 100.0
  joint_limits: 100.0
  rest_pose: 0.1

# Visualization settings
visualization:
  target_color: [255, 0, 0]  # Red
  point_size: 0.02
  sleep_time: 0.05

# Error tolerance settings
tolerance:
  position_error: 0.005  # meters (5mm)
  # orientation_error: 0.017  # radians (~1 degrees)
  orientation_error: 0.087  # radians (~5 degrees)

# Batch search space settings
search_space:
  line_length: 0.15
  num_timesteps: 750
  z_height: 0.0
  x_range: [-0.2, 0.2, 0.1]      # [start, stop, step]
  y_range: [-0.6, -0.4, 0.1]    # [start, stop, step]
  angle_range: [0, 1.5707963268, 0.09817477] # [start, stop (2*pi), step (pi/4)]